### ISSUE TITLE
how to submit the Code

### ISSUE THREAD

**Issue by ayushg-nitw** [Sajantoor/leetcode-api#2]
Give me the full Api where i will post request so that it get submits to the leetcode user online using postman.
api/v1/leetcode/questions/two-sum/submit what is initial  part of this request. It is not working. Can u elaborate fully

**Comment by Sajantoor** [comment]
Hi, I apologize for the delay.

The application is no longer being hosted so you would have to host the application yourself. All the information about the submit API as well as other APIs are in the swagger. You would have to provide the 2 headers, `LEETCODE_SESSION` and `X-CSRF-Token` details about how to get them are in the README. Then you have to provide the body, `lang` is the language, for example if you want to submit java code it would be `java`, C++ would be `cpp`. `question_id` is the question id, for example for two-sum it is 1. `typed_code` is the code you want to submit. 

![image](https://github.com/user-attachments/assets/71489957-6255-4e21-8ad5-54a9b14fa3b4)

I hope this is helpful, if you have another other questions please reopen the issue and feel free to ask. I will try to respond in a quicker manner.
