### ISSUE TITLE
Hey, the host doesnt seen to be working anymore as it returns a 404

### ISSUE THREAD

**Issue by SD-W1972** [Sajantoor/leetcode-api#3]
Not exactly an issue and I know its an old repository but I'd love to see your work

**Comment by Sajantoor** [comment]
Hey,
Thanks for the question. Yeah I took the host down, so it's no longer being hosted. You can host it yourself. I need to update the README. There's some more details in (#2). If you have any questions reopen and let me know.

**Comment by SD-W1972** [comment]
I understand, thanks for answering :)
